name: LG_competition
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - pytorch==1.8.0
  - torchvision==0.9.0
  - torchaudio==0.8.0
  - cudatoolkit=11.1
  - pytorch-lightning==1.3.8
  - jupyter
  - timm
  - einops
  - pandas
  - scikit-learn

  - pip:
      - -r requirements.txt