wandb:
  _target_: pytorch_lightning.loggers.wandb.WandbLogger
  project: "LG_hydra_example"
  name: ${run_name}
  save_dir: "."
  sync_step: False
  offline: False # set True to store all logs only locally
